### ISSUE TITLE
Lowercase and uppercase not recognized  

### ISSUE THREAD

**Issue by JacobRammer** [Randpy/PythonBattleshipGame#4]
Lower case locations are not recognized as valid input. Ex: 
jacob, where do you want to place your Carrier(5)? b7
Please insert a valid position.

Same for horizontal / vertical section. Ex:
Do you want to place it horizontal or vertical? (h, v) H
Please insert a valid direction.

 I'll be submitting a PR to fix this after creating the issue.

**Comment by JorritWillaert** [comment]
Thanks for your input!
